MDScreen:
	MDIconButton:
		icon: "language-python"
		pos_hint: {'center_x': .5, 'center_y':.5}
		#md_bg_color: app.theme_cls.primary_color

	MDFloatingActionButton:
		icon: 'android'
		md_bg_color: app.theme_cls.primary_color
		pos_hint: {'center_x': .1, 'center_y':.5}

	MDFlatButton:
		text: 'Hello'
		icon: 'language-python'
		pos_hint: {'center_x': .2, 'center_y':.5}
		md_bg_color: app.theme_cls.primary_light

	MDRaisedButton:
		text: 'Hai'
		pos_hint: {'center_x': .3, 'center_y':.5}
		md_bg_color: app.theme_cls.primary_dark

