MDBoxLayout:
	orientation: 'vertical'

	MDToolbar:
		title: 'Top Toolbar'
		left_action_items: [['menu']]
		right_action_items: [['dots-vertical']]

	MDLabel:
		id: my_label
		text: 'Some Stuff'
		halign: "center"

	MDBottomAppBar:
		MDToolbar:
			title: 'bottom menu'
			left_action_items: [['menu', lambda x: app.presser()]]
			icon: 'git'
			type: 'bottom'
			#mode: 'free-end'
			mode: 'end'
			#mode: 'center'
			#mode: 'free-center'

			#Click the button
			on_action_button: app.presser()