<Welcome>:
    MDFloatLayout:
        md_bg_color: 1,1,1,1
    Image:
        source:'assets/images/welcome.jpg'
        size_hint: .9, .7
        pos_hint: {'center_x': .5, 'center_y': .7}
        allow_stretch: True
    MDLabel:
        text: "H e l l o"
        halign: 'center'
        font_name: 'MAIAN'
        font_size: 15
        pos_hint: {'center_y':.45}
    MDLabel:
        text: 'Selamat Datang di TokoSebelah'
    